customhost = "database-2.culwxou6cuaj.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "abcd1234"
customdb = "company"
custombucket = "wky-company"
customregion = "us-east-1"

# customhost = "database-2.cyltbqip9evc.us-east-1.rds.amazonaws.com"
# customuser = "aws_user"
# custompass = "abcd1234"
# customdb = "itps"
# custombucket = "wky-company"
# customregion = "us-east-1"